nelmio_api_doc:
    documentation:
        info:
            title: API Documentation
            description: API documentation for Project
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
